/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetAllActorSegmentsParams,
  GetOneActorSegmentParams,
  ResponseActorSegment,
  ResponseActorSegments
} from '../../../schemas/core';

import { Fetcher } from '../../../../Fetcher';



  export const getSegmentos = () => {
/**
 * Obtiene un actor_segment
 * @summary Get One Actor Segments
 */
const getOneActorSegment = (
    params: GetOneActorSegmentParams,
 ) => {
      return Fetcher<ResponseActorSegment>(
      {url: `/segments/get/one`, method: 'GET',
        params
    },
      );
    }
  /**
 * Obtiene todos los actor_segmentes
 * @summary Get All Actor Segments
 */
const getAllActorSegments = (
    params?: GetAllActorSegmentsParams,
 ) => {
      return Fetcher<ResponseActorSegments>(
      {url: `/segments/get/all`, method: 'GET',
        params
    },
      );
    }
  return {getOneActorSegment,getAllActorSegments}};
export type GetOneActorSegmentResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSegmentos>['getOneActorSegment']>>>
export type GetAllActorSegmentsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSegmentos>['getAllActorSegments']>>>
