/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import {
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  GetAllActorsParams,
  GetOneActorParams,
  ResponseActor,
  ResponseActors,
  ResponseError
} from '../../../schemas/core';

import { Fetcher } from '../../../../Fetcher';




/**
 * Obtiene una entidad por su ID
 * @summary Get One Actor
 */
export const getOneActor = (
    params: GetOneActorParams,
 signal?: AbortSignal
) => {
      
      
      return Fetcher<ResponseActor>(
      {url: `/actors/get/one`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetOneActorQueryKey = (params?: GetOneActorParams,) => {
    return [
    `/actors/get/one`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetOneActorQueryOptions = <TData = Awaited<ReturnType<typeof getOneActor>>, TError = ResponseError>(params: GetOneActorParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getOneActor>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOneActorQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneActor>>> = ({ signal }) => getOneActor(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getOneActor>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneActorQueryResult = NonNullable<Awaited<ReturnType<typeof getOneActor>>>
export type GetOneActorQueryError = ResponseError


/**
 * @summary Get One Actor
 */

export function createGetOneActor<TData = Awaited<ReturnType<typeof getOneActor>>, TError = ResponseError>(
 params: GetOneActorParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getOneActor>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOneActorQueryOptions(params,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Obtiene todas las entidades
 * @summary Get All Actors
 */
export const getAllActors = (
    params?: GetAllActorsParams,
 signal?: AbortSignal
) => {
      
      
      return Fetcher<ResponseActors>(
      {url: `/actors/get/all`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAllActorsQueryKey = (params?: GetAllActorsParams,) => {
    return [
    `/actors/get/all`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllActorsQueryOptions = <TData = Awaited<ReturnType<typeof getAllActors>>, TError = ResponseError>(params?: GetAllActorsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllActors>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllActorsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllActors>>> = ({ signal }) => getAllActors(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getAllActors>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllActorsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllActors>>>
export type GetAllActorsQueryError = ResponseError


/**
 * @summary Get All Actors
 */

export function createGetAllActors<TData = Awaited<ReturnType<typeof getAllActors>>, TError = ResponseError>(
 params?: GetAllActorsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllActors>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllActorsQueryOptions(params,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




