/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body for registering a new user.
 */
export interface RequestRegister {
  /**
   * Contraseña del usuario
   * @minLength 8
   * @maxLength 128
   */
  password: string;
  /**
   * Correo electrónico válido
   * @minLength 8
   * @maxLength 256
   */
  email: string;
  /**
   * Nombre de usuario
   * @minLength 4
   * @maxLength 128
   */
  username: string;
}
