/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type {
  BodyUploadFile,
  GetOneFileParams,
  RequestEditFile,
  ResponseFile,
  ResponseFiles,
  ResponseMessage
} from '../../../schemas/auth';

import { Fetcher } from '../../../../Fetcher';



  export const getArchivos = () => {
/**
 * Function that gets a single file
 * @summary Get Media
 */
const getOneFile = (
    params: GetOneFileParams,
 ) => {
      return Fetcher<void>(
      {url: `/files/get/one`, method: 'GET',
        params
    },
      );
    }
  /**
 * Function that gets all of a users files
 * @summary Get All Media
 */
const getAllFiles = (
    
 ) => {
      return Fetcher<ResponseFiles>(
      {url: `/files/get/all`, method: 'GET'
    },
      );
    }
  /**
 * Function that uploads a file
 * @summary Upload
 */
const uploadFile = (
    bodyUploadFile: BodyUploadFile,
 ) => {const formData = new FormData();
formData.append(`file`, bodyUploadFile.file)

      return Fetcher<ResponseMessage>(
      {url: `/files/upload`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData
    },
      );
    }
  /**
 * Function to edit a file.
 * @summary Edit Media
 */
const replaceFile = (
    requestEditFile: RequestEditFile,
 ) => {
      return Fetcher<ResponseFile>(
      {url: `/files/edit`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: requestEditFile
    },
      );
    }
  /**
 * Function to delete a file.
 * @summary Delete Media
 */
const deleteFile = (
    id: string,
 ) => {
      return Fetcher<ResponseMessage>(
      {url: `/files/delete/${id}`, method: 'DELETE'
    },
      );
    }
  return {getOneFile,getAllFiles,uploadFile,replaceFile,deleteFile}};
export type GetOneFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getArchivos>['getOneFile']>>>
export type GetAllFilesResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getArchivos>['getAllFiles']>>>
export type UploadFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getArchivos>['uploadFile']>>>
export type ReplaceFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getArchivos>['replaceFile']>>>
export type DeleteFileResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getArchivos>['deleteFile']>>>
