"""initial

Revision ID: d103cd1a7b66
Revises: 
Create Date: 2026-05-07 00:09:37.972050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd103cd1a7b66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_segments',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    schema='actors'
    )
    op.create_table('forms',
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anno'),
    schema='forms'
    )
    op.create_table('section_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_table('comment_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('field_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('file_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=255), nullable=False),
    sa.Column('max_size', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('log_action_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('notification_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('relational_operators',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('roles',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('rule_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('submission_status_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('user_tiers',
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('max_file_size', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('storage_quota', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('max_requests_per_minute', sa.Integer(), nullable=False),
    sa.Column('priority_level', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('answers',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('card_entry_id', sa.UUID(), nullable=True),
    sa.Column('discriminator', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_entry_id'], ['submissions.answers_card_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['forms.fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('answers_card_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('card_template_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('card_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_template_id'], ['forms.card_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['submissions.answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['forms.questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('users',
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('media_usage', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['reference.user_tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='auth'
    )
    op.create_table('answers_boolean',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['submissions.answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('answers_date',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['submissions.answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('answers_multi_choice',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['submissions.answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('answers_numeric',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['submissions.answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('answers_texts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['submissions.answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('actors',
    sa.Column('actor_segment_id', sa.UUID(), nullable=False),
    sa.Column('contact_person_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('mission', sa.Text(), nullable=False),
    sa.Column('vision', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_segment_id'], ['actors.actor_segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_person_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    schema='actors'
    )
    op.create_table('logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_action_type_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.Enum('LOG_ACTION_TYPES', 'FILE_TYPES', 'ROLES', 'USER_TIERS', 'USERS', 'LOGS', 'REFRESH_SESSIONS', 'USER_DETAILS', 'FILES', 'USER_PROFILES', 'LINK_USER_FILE', 'COMMENT_TYPES', 'NOTIFICATION_TYPES', 'COMMENTS', 'NOTIFICATIONS', 'ACTOR_SEGMENTS', 'ACTORS', 'LINK_USER_ACTOR', 'FIELD_TYPES', 'FORMS', 'SECTION_TYPES', 'SECTIONS', 'INFORMATIONS', 'QUESTIONS', 'CARD_TEMPLATES', 'FIELD_GROUPS', 'FIELDS', 'FIELD_CHOICES', 'RELATIONAL_OPERATORS', 'RULE_TYPES', 'SECTION_DEPENDENCIES', 'FIELD_DEPENDENCIES', 'FIELD_RULES', 'SUBMISSION_STATUS_TYPES', 'SUBMISSIONS', 'ASSIGNMENTS', 'CRITERIA', 'GRADES', 'RESULTS', 'ANSWERS_CARD_ENTRY', 'ANSWERS', 'ANSWERS_BOOLEAN', 'ANSWERS_DATE', 'ANSWERS_FILE', 'ANSWERS_MULTI_CHOICE', 'ANSWERS_NUMERIC', 'ANSWERS_SINGLE_CHOICE', 'ANSWERS_TEXT', 'LINK_USER_SUBMISSION', 'LINK_CHOICE_MULTICHOICE', name='targettableenum'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['log_action_type_id'], ['reference.log_action_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_table('refresh_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('refresh_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('user_details',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email_pro', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_pro'),
    sa.UniqueConstraint('user_id'),
    schema='auth'
    )
    op.create_table('files',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_type_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('filehash', sa.String(length=64), nullable=False),
    sa.Column('filesize', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_type_id'], ['reference.file_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='files'
    )
    op.create_index(op.f('ix_files_files_filehash'), 'files', ['filehash'], unique=True, schema='files')
    op.create_table('comments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('comment_type_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.Enum('LOG_ACTION_TYPES', 'FILE_TYPES', 'ROLES', 'USER_TIERS', 'USERS', 'LOGS', 'REFRESH_SESSIONS', 'USER_DETAILS', 'FILES', 'USER_PROFILES', 'LINK_USER_FILE', 'COMMENT_TYPES', 'NOTIFICATION_TYPES', 'COMMENTS', 'NOTIFICATIONS', 'ACTOR_SEGMENTS', 'ACTORS', 'LINK_USER_ACTOR', 'FIELD_TYPES', 'FORMS', 'SECTION_TYPES', 'SECTIONS', 'INFORMATIONS', 'QUESTIONS', 'CARD_TEMPLATES', 'FIELD_GROUPS', 'FIELDS', 'FIELD_CHOICES', 'RELATIONAL_OPERATORS', 'RULE_TYPES', 'SECTION_DEPENDENCIES', 'FIELD_DEPENDENCIES', 'FIELD_RULES', 'SUBMISSION_STATUS_TYPES', 'SUBMISSIONS', 'ASSIGNMENTS', 'CRITERIA', 'GRADES', 'RESULTS', 'ANSWERS_CARD_ENTRY', 'ANSWERS', 'ANSWERS_BOOLEAN', 'ANSWERS_DATE', 'ANSWERS_FILE', 'ANSWERS_MULTI_CHOICE', 'ANSWERS_NUMERIC', 'ANSWERS_SINGLE_CHOICE', 'ANSWERS_TEXT', 'LINK_USER_SUBMISSION', 'LINK_CHOICE_MULTICHOICE', name='targettableenum'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['comment_type_id'], ['reference.comment_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='interactions'
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['notification_type_id'], ['reference.notification_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='interactions'
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id'),
    sa.UniqueConstraint('user_id'),
    schema='auth'
    )
    op.create_table('sections',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('section_type_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('helper', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.forms.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['forms.sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_type_id'], ['forms.section_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_index('idx_sections_form_id', 'sections', ['form_id'], unique=False, schema='forms')
    op.create_index('idx_sections_parent_display_order', 'sections', ['parent_id', 'display_order'], unique=False, schema='forms')
    op.create_index('idx_sections_parent_id', 'sections', ['parent_id'], unique=False, schema='forms')
    op.create_index('idx_sections_section_type_id', 'sections', ['section_type_id'], unique=False, schema='forms')
    op.create_table('user_actor_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['reference.roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'actor_id', 'role_id', 'id'),
    schema='links'
    )
    op.create_table('user_file_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['reference.roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'file_id', 'role_id', 'id'),
    schema='links'
    )
    op.create_table('answers_file',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['submissions.answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value_id'], ['files.files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('submissions',
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.forms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['reference.submission_status_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('information',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['forms.sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_table('questions',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('is_loop', sa.Boolean(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('helper', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.forms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['forms.sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_table('results',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='grading'
    )
    op.create_table('user_submission_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['reference.roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'submission_id', 'role_id', 'id'),
    schema='links'
    )
    op.create_table('section_dependencies',
    sa.Column('target_section_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_section_id', sa.UUID(), nullable=False),
    sa.Column('relational_operator_id', sa.UUID(), nullable=False),
    sa.Column('expected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_section_id'], ['forms.sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relational_operator_id'], ['reference.relational_operators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_section_id'], ['forms.sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rules'
    )
    op.create_table('card_templates',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('helper', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['forms.questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_table('criteria',
    sa.Column('question_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['forms.questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='grading'
    )
    op.create_table('field_groups',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('card_template_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_template_id'], ['forms.card_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.forms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['forms.questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_table('grades',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('criterion_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['grading.criteria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submissions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='grading'
    )
    op.create_table('fields',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('field_group_id', sa.UUID(), nullable=False),
    sa.Column('field_type_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['field_group_id'], ['forms.field_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_type_id'], ['reference.field_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.forms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_table('field_choices',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['forms.fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_table('field_dependencies',
    sa.Column('target_field_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_field_id', sa.UUID(), nullable=False),
    sa.Column('relational_operator_id', sa.UUID(), nullable=False),
    sa.Column('expected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_field_id'], ['forms.fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relational_operator_id'], ['reference.relational_operators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_field_id'], ['forms.fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rules'
    )
    op.create_table('field_rules',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('rule_type_id', sa.UUID(), nullable=False),
    sa.Column('rule_value', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['forms.fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_type_id'], ['reference.rule_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rules'
    )
    op.create_table('choice_multichoice_links',
    sa.Column('choice_id', sa.UUID(), nullable=False),
    sa.Column('multi_choice_answer_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['forms.field_choices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['multi_choice_answer_id'], ['submissions.answers_multi_choice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('choice_id', 'multi_choice_answer_id', 'id'),
    schema='links'
    )
    op.create_table('answers_single_choice',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['submissions.answers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value_id'], ['forms.field_choices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answers_single_choice', schema='submissions')
    op.drop_table('choice_multichoice_links', schema='links')
    op.drop_table('field_rules', schema='rules')
    op.drop_table('field_dependencies', schema='rules')
    op.drop_table('field_choices', schema='forms')
    op.drop_table('fields', schema='forms')
    op.drop_table('grades', schema='grading')
    op.drop_table('field_groups', schema='forms')
    op.drop_table('criteria', schema='grading')
    op.drop_table('card_templates', schema='forms')
    op.drop_table('section_dependencies', schema='rules')
    op.drop_table('user_submission_links', schema='links')
    op.drop_table('results', schema='grading')
    op.drop_table('questions', schema='forms')
    op.drop_table('information', schema='forms')
    op.drop_table('submissions', schema='submissions')
    op.drop_table('answers_file', schema='submissions')
    op.drop_table('user_file_links', schema='links')
    op.drop_table('user_actor_links', schema='links')
    op.drop_index('idx_sections_section_type_id', table_name='sections', schema='forms')
    op.drop_index('idx_sections_parent_id', table_name='sections', schema='forms')
    op.drop_index('idx_sections_parent_display_order', table_name='sections', schema='forms')
    op.drop_index('idx_sections_form_id', table_name='sections', schema='forms')
    op.drop_table('sections', schema='forms')
    op.drop_table('user_profiles', schema='auth')
    op.drop_table('notifications', schema='interactions')
    op.drop_table('comments', schema='interactions')
    op.drop_index(op.f('ix_files_files_filehash'), table_name='files', schema='files')
    op.drop_table('files', schema='files')
    op.drop_table('user_details', schema='auth')
    op.drop_table('refresh_sessions', schema='auth')
    op.drop_table('logs', schema='audit')
    op.drop_table('actors', schema='actors')
    op.drop_table('answers_texts', schema='submissions')
    op.drop_table('answers_numeric', schema='submissions')
    op.drop_table('answers_multi_choice', schema='submissions')
    op.drop_table('answers_date', schema='submissions')
    op.drop_table('answers_boolean', schema='submissions')
    op.drop_table('users', schema='auth')
    op.drop_table('answers_card_entry', schema='submissions')
    op.drop_table('answers', schema='submissions')
    op.drop_table('user_tiers', schema='reference')
    op.drop_table('submission_status_types', schema='reference')
    op.drop_table('rule_types', schema='reference')
    op.drop_table('roles', schema='reference')
    op.drop_table('relational_operators', schema='reference')
    op.drop_table('notification_types', schema='reference')
    op.drop_table('log_action_types', schema='reference')
    op.drop_table('file_types', schema='reference')
    op.drop_table('field_types', schema='reference')
    op.drop_table('comment_types', schema='reference')
    op.drop_table('section_types', schema='forms')
    op.drop_table('forms', schema='forms')
    op.drop_table('actor_segments', schema='actors')
    # ### end Alembic commands ###
