/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type { BodyLoginUserClientId } from './bodyLoginUserClientId';
import type { BodyLoginUserClientSecret } from './bodyLoginUserClientSecret';

export interface BodyLoginUser {
  /** @pattern ^password$ */
  grant_type: string;
  username: string;
  password: string;
  scope?: string;
  client_id?: BodyLoginUserClientId;
  client_secret?: BodyLoginUserClientSecret;
}
