/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */

/**
 * Modelo para representar un token de refresco.
 */
export interface RefreshToken {
  /**
   * Token de refresco.
   * @minLength 36
   * @maxLength 512
   */
  refresh_token: string;
  /**
   * Tipo de token
   * @minLength 2
   * @maxLength 128
   */
  token_type?: string;
}
