services:  
  persister:
    image: labcapital/apps:IIP-Persister
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - github_token_commons
        - github_token_iip

secrets:
  github_token_commons:
    environment: GITHUB_TOKEN_COMMONS 
  github_token_iip:
    environment: GITHUB_TOKEN_IIP
