/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import {
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  GetAllFormsParams,
  GetOneFormParams,
  ResponseError,
  ResponseForm,
  ResponseForms
} from '../../../schemas/core';

import { Fetcher } from '../../../../Fetcher';




/**
 * Obtiene una edición de índice
 * @summary Get One Form
 */
export const getOneForm = (
    params: GetOneFormParams,
 signal?: AbortSignal
) => {
      
      
      return Fetcher<ResponseForm>(
      {url: `/forms/get/one`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetOneFormQueryKey = (params?: GetOneFormParams,) => {
    return [
    `/forms/get/one`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetOneFormQueryOptions = <TData = Awaited<ReturnType<typeof getOneForm>>, TError = ResponseError>(params: GetOneFormParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getOneForm>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOneFormQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneForm>>> = ({ signal }) => getOneForm(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getOneForm>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneFormQueryResult = NonNullable<Awaited<ReturnType<typeof getOneForm>>>
export type GetOneFormQueryError = ResponseError


/**
 * @summary Get One Form
 */

export function createGetOneForm<TData = Awaited<ReturnType<typeof getOneForm>>, TError = ResponseError>(
 params: GetOneFormParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getOneForm>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOneFormQueryOptions(params,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Obtiene todas las ediciones de índices
 * @summary Get All Forms
 */
export const getAllForms = (
    params?: GetAllFormsParams,
 signal?: AbortSignal
) => {
      
      
      return Fetcher<ResponseForms>(
      {url: `/forms/get/all`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAllFormsQueryKey = (params?: GetAllFormsParams,) => {
    return [
    `/forms/get/all`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllFormsQueryOptions = <TData = Awaited<ReturnType<typeof getAllForms>>, TError = ResponseError>(params?: GetAllFormsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllForms>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllFormsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllForms>>> = ({ signal }) => getAllForms(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getAllForms>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllFormsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllForms>>>
export type GetAllFormsQueryError = ResponseError


/**
 * @summary Get All Forms
 */

export function createGetAllForms<TData = Awaited<ReturnType<typeof getAllForms>>, TError = ResponseError>(
 params?: GetAllFormsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllForms>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllFormsQueryOptions(params,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




