keys:
  - &yubikey age1yubikey1q29kztksvl8elnwuef80evq3sfwu7yn24dscp7yakg5xyal0suyhxd5hjtf
  - &jj_laptop age18n5zera0mtd6uzmvxuu7f7ep9lrulvayjvpw0g53h99jv0508q2sjh9jtf
  - &jhonatan age1ks66sntukmkht6mz0545xqs3zg6kzm35c88necpfrqegtlt8wqfsj2myur

creation_rules:
  - path_regex: \.(yaml|json|env)$
    key_groups:
      - age:
          - *yubikey
          - *jj_laptop
          - *jhonatan
