services:
  nginx:
    container_name: iip_nginx
    image: nginx:latest
    restart: unless-stopped
    secrets:
      - https_public
      - https_private
    networks:
      - iip_nginx
    ports:
      - "${PORT_AUTH}:${PORT_AUTH}"
      - "${PORT_CORE}:${PORT_CORE}"
      - "${PORT_IA_AGENT}:${PORT_IA_AGENT}"
      # - "${PORT_STAT}:${PORT_STAT}"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  db:
    container_name: iip_db_auth
    image: postgres:18-bookworm
    env_file: ./.env
    secrets:
      - postgres_password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    networks:
      - iip_db_net
      - pgadmin_net
    volumes:
      - postgresql:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 5
  
  persister:
    container_name: iip_persister
    image: labcapital/apps:IIP-Persister
    env_file: ./.env
    secrets:
      - postgres_password
      - users_file
    networks:
      - iip_db_net

  # api_stats:
  #   container_name: iip_stats
  #   image: labcapital/apps:Stats
  #   env_file: ./.env
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=true"
  #   environment:
  #     PORT: "${PORT_STAT}"
  #   expose:
  #     - "${PORT_STAT}"
  #   networks:
  #     - iip_nginx
  #     - iip_backend_net
  #   depends_on:
  #     - api_auth

  api_auth:
    container_name: iip_api_auth
    image: labcapital/apps:IIP-Auth
    env_file: ./.env
    secrets:
      - jwt_private_key
      - jwt_public_key
      - fernet_key
    networks:
      - iip_db_net
      - iip_nginx
    depends_on:
      db:
        condition: service_healthy

  api_core:
    container_name: iip_api_core
    image: labcapital/apps:IIP-Core
    env_file: ./.env
    secrets:
      - jwt_public_key
    networks:
      - iip_db_net
      - iip_nginx

  api_ia_agent:
    container_name: iip_api_ia_agent
    image: labcapital/apps:IIP-IA-Agent
    env_file: ./.env
    secrets:
      - jwt_public_key
    networks:
      - iip_db_net
      - iip_nginx

networks:
  iip_db_net:
    driver: bridge
    name: iip_db_network

  iip_nginx:
    driver: bridge
    name: iip_nginx_network

  pgadmin_net:
    name: pgadmin_network
    external: true

volumes:
  postgresql:
    name: stats_vol_pg

secrets:
  fernet_key:
    file: ../Secrets/fernet
  github_token:
    file: ../Secrets/gh_token
  postgres_password:
    file: ../Secrets/postgres
  jwt_public_key:
    file: ../Secrets/jwt_public.pem
  jwt_private_key:
    file: ../Secrets/jwt_private.pem
  https_public:
    file: ../Secrets/vd-cert.crt
  https_private:
    file: ../Secrets/vd-cert.key
  users_file:
    file: ../Secrets/users.toml