events {}

http {
    server {
        listen 8001 ssl;
        server_name localhost;

        ssl_certificate     /run/secrets/https_public;
        ssl_certificate_key /run/secrets/https_private;

    	location / {
    		proxy_pass http://api_auth:8001;
    		proxy_set_header Host $host;
    		proxy_set_header X-Real-IP $remote_addr;
    		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    		proxy_set_header X-Forwarded-Proto $scheme;
    	}
    }
    server {
        listen 8002 ssl;
        server_name localhost;

        ssl_certificate     /run/secrets/https_public;
        ssl_certificate_key /run/secrets/https_private;

    	location / {
    		proxy_pass http://api_core:8002;
    		proxy_set_header Host $host;
    		proxy_set_header X-Real-IP $remote_addr;
    		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    		proxy_set_header X-Forwarded-Proto $scheme;
    	}
    }
}
