/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import {
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  GetAllActorSegmentsParams,
  GetOneActorSegmentParams,
  ResponseActorSegment,
  ResponseActorSegments,
  ResponseError
} from '../../../schemas/core';

import { Fetcher } from '../../../../Fetcher';




/**
 * Obtiene un actor_segment
 * @summary Get One Actor Segments
 */
export const getOneActorSegment = (
    params: GetOneActorSegmentParams,
 signal?: AbortSignal
) => {
      
      
      return Fetcher<ResponseActorSegment>(
      {url: `/segments/get/one`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetOneActorSegmentQueryKey = (params?: GetOneActorSegmentParams,) => {
    return [
    `/segments/get/one`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetOneActorSegmentQueryOptions = <TData = Awaited<ReturnType<typeof getOneActorSegment>>, TError = ResponseError>(params: GetOneActorSegmentParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getOneActorSegment>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOneActorSegmentQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneActorSegment>>> = ({ signal }) => getOneActorSegment(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getOneActorSegment>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneActorSegmentQueryResult = NonNullable<Awaited<ReturnType<typeof getOneActorSegment>>>
export type GetOneActorSegmentQueryError = ResponseError


/**
 * @summary Get One Actor Segments
 */

export function createGetOneActorSegment<TData = Awaited<ReturnType<typeof getOneActorSegment>>, TError = ResponseError>(
 params: GetOneActorSegmentParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getOneActorSegment>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOneActorSegmentQueryOptions(params,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Obtiene todos los actor_segmentes
 * @summary Get All Actor Segments
 */
export const getAllActorSegments = (
    params?: GetAllActorSegmentsParams,
 signal?: AbortSignal
) => {
      
      
      return Fetcher<ResponseActorSegments>(
      {url: `/segments/get/all`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAllActorSegmentsQueryKey = (params?: GetAllActorSegmentsParams,) => {
    return [
    `/segments/get/all`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllActorSegmentsQueryOptions = <TData = Awaited<ReturnType<typeof getAllActorSegments>>, TError = ResponseError>(params?: GetAllActorSegmentsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllActorSegments>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllActorSegmentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllActorSegments>>> = ({ signal }) => getAllActorSegments(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getAllActorSegments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllActorSegmentsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllActorSegments>>>
export type GetAllActorSegmentsQueryError = ResponseError


/**
 * @summary Get All Actor Segments
 */

export function createGetAllActorSegments<TData = Awaited<ReturnType<typeof getAllActorSegments>>, TError = ResponseError>(
 params?: GetAllActorSegmentsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllActorSegments>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllActorSegmentsQueryOptions(params,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




