/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */

export type GetAllFormsParams = {
/**
 * Return detailed data
 */
detailed?: boolean;
};
