/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type { ResponseActorDescription } from './responseActorDescription';
import type { ResponseActorActorSegment } from './responseActorActorSegment';
import type { ResponseActorMission } from './responseActorMission';
import type { ResponseActorVision } from './responseActorVision';

/**
 * Modelo para representar una solicitud de entidad.
 */
export interface ResponseActor {
  /** UUID del objeto */
  id: string;
  /**
   * Nombre de la entidad
   * @minLength 1
   * @maxLength 512
   */
  name: string;
  /** Descripción de la entidad */
  description?: ResponseActorDescription;
  /** ActorSegment de la entidad */
  actor_segment?: ResponseActorActorSegment;
  /** Misión de la entidad */
  mission?: ResponseActorMission;
  /** Visión de la entidad */
  vision?: ResponseActorVision;
}
