/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type { ResponseWeb } from './responseWeb';
import type { ResponseMobile } from './responseMobile';

export type LoginUser200 = ResponseWeb | ResponseMobile;
