/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body for editing a file.
 */
export interface RequestEditFile {
  /** UUID del objeto */
  id: string;
  /**
   * Recibe el nuevo nombre del archivo
   * @minLength 1
   * @maxLength 256
   */
  filename: string;
}
