/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */

/**
 * Modelo para representar un registro.
 */
export interface ResponseRegister {
  /**
   * Correo electrónico válido
   * @minLength 8
   * @maxLength 256
   */
  email: string;
  /**
   * Nombre de usuario
   * @minLength 4
   * @maxLength 128
   */
  username: string;
  /**
   * Un mensaje que indica que el registro fue exitoso.
   * @minLength 2
   * @maxLength 256
   */
  message?: string;
}
