/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */

/**
 * Modelo para representar un logout.
 */
export interface ResponseLogout {
  /**
   * Un mensaje que indica que el logout fue exitoso.
   * @minLength 2
   * @maxLength 256
   */
  message?: string;
}
