/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetAllResultsParams,
  GetOneResultsParams
} from '../../../schemas/core';

import { Fetcher } from '../../../../Fetcher';



  export const getResultados = () => {
/**
 * Obtiene una edición de índice
 * @summary Get One Form
 */
const getOneResults = (
    params: GetOneResultsParams,
 ) => {
      return Fetcher<unknown>(
      {url: `/results/get/one`, method: 'GET',
        params
    },
      );
    }
  /**
 * Obtiene todas las ediciones de índices
 * @summary Get All Forms
 */
const getAllResults = (
    params?: GetAllResultsParams,
 ) => {
      return Fetcher<unknown>(
      {url: `/results/get/all`, method: 'GET',
        params
    },
      );
    }
  return {getOneResults,getAllResults}};
export type GetOneResultsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getResultados>['getOneResults']>>>
export type GetAllResultsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getResultados>['getAllResults']>>>
