/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type { ResponseActorSegment } from './responseActorSegment';

/**
 * Modelo para representar una lista de actor_segmentes de forma resumida.
 */
export interface ResponseActorSegments {
  /**
   * Lista de actor_segmentes
   * @minItems 1
   * @maxItems 512
   */
  actor_segments: ResponseActorSegment[];
}
