/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type { ResponseActor } from './responseActor';

/**
 * Lista de actores
 */
export type ResponseActorSegmentActors = ResponseActor[] | null;
