/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation,
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  BodyUploadFile,
  GetOneFileParams,
  RequestEditFile,
  ResponseError,
  ResponseFile,
  ResponseFiles,
  ResponseMessage
} from '../../../schemas/auth';

import { Fetcher } from '../../../../Fetcher';




/**
 * Function that gets a single file
 * @summary Get Media
 */
export const getOneFile = (
    params: GetOneFileParams,
 signal?: AbortSignal
) => {
      
      
      return Fetcher<void>(
      {url: `/files/get/one`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetOneFileQueryKey = (params?: GetOneFileParams,) => {
    return [
    `/files/get/one`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetOneFileQueryOptions = <TData = Awaited<ReturnType<typeof getOneFile>>, TError = ResponseError>(params: GetOneFileParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getOneFile>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOneFileQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneFile>>> = ({ signal }) => getOneFile(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getOneFile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneFileQueryResult = NonNullable<Awaited<ReturnType<typeof getOneFile>>>
export type GetOneFileQueryError = ResponseError


/**
 * @summary Get Media
 */

export function createGetOneFile<TData = Awaited<ReturnType<typeof getOneFile>>, TError = ResponseError>(
 params: GetOneFileParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getOneFile>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOneFileQueryOptions(params,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Function that gets all of a users files
 * @summary Get All Media
 */
export const getAllFiles = (
    
 signal?: AbortSignal
) => {
      
      
      return Fetcher<ResponseFiles>(
      {url: `/files/get/all`, method: 'GET', signal
    },
      );
    }
  



export const getGetAllFilesQueryKey = () => {
    return [
    `/files/get/all`
    ] as const;
    }

    
export const getGetAllFilesQueryOptions = <TData = Awaited<ReturnType<typeof getAllFiles>>, TError = ResponseError>( options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllFiles>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllFilesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllFiles>>> = ({ signal }) => getAllFiles(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getAllFiles>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllFilesQueryResult = NonNullable<Awaited<ReturnType<typeof getAllFiles>>>
export type GetAllFilesQueryError = ResponseError


/**
 * @summary Get All Media
 */

export function createGetAllFiles<TData = Awaited<ReturnType<typeof getAllFiles>>, TError = ResponseError>(
  options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllFiles>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllFilesQueryOptions(options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Function that uploads a file
 * @summary Upload
 */
export const uploadFile = (
    bodyUploadFile: BodyUploadFile,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, bodyUploadFile.file)

      return Fetcher<ResponseMessage>(
      {url: `/files/upload`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }
  


export const getUploadFileMutationOptions = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof uploadFile>>, TError,{data: BodyUploadFile}, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof uploadFile>>, TError,{data: BodyUploadFile}, TContext> => {

const mutationKey = ['uploadFile'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadFile>>, {data: BodyUploadFile}> = (props) => {
          const {data} = props ?? {};

          return  uploadFile(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadFileMutationResult = NonNullable<Awaited<ReturnType<typeof uploadFile>>>
    export type UploadFileMutationBody = BodyUploadFile
    export type UploadFileMutationError = ResponseError

    /**
 * @summary Upload
 */
export const createUploadFile = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof uploadFile>>, TError,{data: BodyUploadFile}, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof uploadFile>>,
        TError,
        {data: BodyUploadFile},
        TContext
      > => {

      const mutationOptions = getUploadFileMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * Function to edit a file.
 * @summary Edit Media
 */
export const replaceFile = (
    requestEditFile: RequestEditFile,
 ) => {
      
      
      return Fetcher<ResponseFile>(
      {url: `/files/edit`, method: 'PUT',
      headers: {'Content-Type': 'application/json', },
      data: requestEditFile
    },
      );
    }
  


export const getReplaceFileMutationOptions = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof replaceFile>>, TError,{data: RequestEditFile}, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof replaceFile>>, TError,{data: RequestEditFile}, TContext> => {

const mutationKey = ['replaceFile'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof replaceFile>>, {data: RequestEditFile}> = (props) => {
          const {data} = props ?? {};

          return  replaceFile(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReplaceFileMutationResult = NonNullable<Awaited<ReturnType<typeof replaceFile>>>
    export type ReplaceFileMutationBody = RequestEditFile
    export type ReplaceFileMutationError = ResponseError

    /**
 * @summary Edit Media
 */
export const createReplaceFile = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof replaceFile>>, TError,{data: RequestEditFile}, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof replaceFile>>,
        TError,
        {data: RequestEditFile},
        TContext
      > => {

      const mutationOptions = getReplaceFileMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * Function to delete a file.
 * @summary Delete Media
 */
export const deleteFile = (
    id: string,
 ) => {
      
      
      return Fetcher<ResponseMessage>(
      {url: `/files/delete/${id}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteFileMutationOptions = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteFile>>, TError,{id: string}, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof deleteFile>>, TError,{id: string}, TContext> => {

const mutationKey = ['deleteFile'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteFile>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  deleteFile(id,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteFileMutationResult = NonNullable<Awaited<ReturnType<typeof deleteFile>>>
    
    export type DeleteFileMutationError = ResponseError

    /**
 * @summary Delete Media
 */
export const createDeleteFile = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof deleteFile>>, TError,{id: string}, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof deleteFile>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDeleteFileMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    