/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type { ResponseActorSegmentDescription } from './responseActorSegmentDescription';
import type { ResponseActorSegmentActors } from './responseActorSegmentActors';

/**
 * Modelo para representar una solicitud de actor_segment.
 */
export interface ResponseActorSegment {
  /** UUID del objeto */
  id: string;
  /**
   * Nombre del actor_segment
   * @minLength 1
   * @maxLength 512
   */
  name: string;
  /** Descripción del actor_segment */
  description?: ResponseActorSegmentDescription;
  /** Lista de actores */
  actors?: ResponseActorSegmentActors;
}
