/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type { ResponseFormName } from './responseFormName';
import type { ResponseFormDescription } from './responseFormDescription';
import type { ResponseFormData } from './responseFormData';

/**
 * Modelo para representar una edición de índice de forma resumida.
 */
export interface ResponseForm {
  /** UUID del objeto */
  id: string;
  /**
   * Año del índice
   * @minimum 1900
   * @maximum 2100
   */
  anno: number;
  /** Nombre del índice */
  name?: ResponseFormName;
  /** Descripción del índice */
  description?: ResponseFormDescription;
  /** Datos del índice */
  data?: ResponseFormData;
}
