/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type { ItemError } from './itemError';

/**
 * Modelo que representa una respuesta de error de validación.
 */
export interface ResponseError {
  /**
   * Lista de errores
   * @minItems 1
   * @maxItems 512
   */
  errors: ItemError[];
  /**
   * Trace of the validation failure
   * @minLength 1
   * @maxLength 512
   */
  trace: string;
}
