/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */

export * from './getAllActorSegmentsParams';
export * from './getAllActorsParams';
export * from './getAllFormsParams';
export * from './getAllResultsParams';
export * from './getOneActorParams';
export * from './getOneActorSegmentParams';
export * from './getOneFormParams';
export * from './getOneResultsParams';
export * from './itemError';
export * from './responseActor';
export * from './responseActorActorSegment';
export * from './responseActorDescription';
export * from './responseActorMission';
export * from './responseActorSegment';
export * from './responseActorSegmentActors';
export * from './responseActorSegmentDescription';
export * from './responseActorSegments';
export * from './responseActorVision';
export * from './responseActors';
export * from './responseError';
export * from './responseForm';
export * from './responseFormData';
export * from './responseFormDescription';
export * from './responseFormName';
export * from './responseForms';