/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type { ResponseActor } from './responseActor';

/**
 * Modelo para representar una lista de entidades de forma resumida.
 */
export interface ResponseActors {
  /**
   * Lista de entidades
   * @minItems 1
   * @maxItems 512
   */
  actors: ResponseActor[];
}
