/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type { ResponseForm } from './responseForm';

/**
 * Modelo para representar una lista de índices de forma resumida.
 */
export interface ResponseForms {
  /**
   * Lista de índices
   * @minItems 1
   * @maxItems 512
   */
  form_editions: ResponseForm[];
}
