/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import {
  createMutation
} from '@tanstack/svelte-query';
import type {
  CreateMutationOptions,
  CreateMutationResult,
  MutationFunction,
  QueryClient
} from '@tanstack/svelte-query';

import type {
  BodyLoginUser,
  LoginUser200,
  LogoutUserBody,
  ReauthUser200,
  ReauthUserBody,
  RequestRegister,
  ResponseError,
  ResponseLogout,
  ResponseRegister
} from '../../../schemas/auth';

import { Fetcher } from '../../../../Fetcher';




/**
 * Function for registering
 * @summary Register
 */
export const registerUser = (
    requestRegister: RequestRegister,
 signal?: AbortSignal
) => {
      
      const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`password`, requestRegister.password)
formUrlEncoded.append(`email`, requestRegister.email)
formUrlEncoded.append(`username`, requestRegister.username)

      return Fetcher<ResponseRegister>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      );
    }
  


export const getRegisterUserMutationOptions = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RequestRegister}, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RequestRegister}, TContext> => {

const mutationKey = ['registerUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof registerUser>>, {data: RequestRegister}> = (props) => {
          const {data} = props ?? {};

          return  registerUser(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RegisterUserMutationResult = NonNullable<Awaited<ReturnType<typeof registerUser>>>
    export type RegisterUserMutationBody = RequestRegister
    export type RegisterUserMutationError = ResponseError

    /**
 * @summary Register
 */
export const createRegisterUser = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof registerUser>>, TError,{data: RequestRegister}, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof registerUser>>,
        TError,
        {data: RequestRegister},
        TContext
      > => {

      const mutationOptions = getRegisterUserMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * Function for logging in
 * @summary Login
 */
export const loginUser = (
    bodyLoginUser: BodyLoginUser,
 signal?: AbortSignal
) => {
      
      const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`grant_type`, bodyLoginUser.grant_type)
formUrlEncoded.append(`username`, bodyLoginUser.username)
formUrlEncoded.append(`password`, bodyLoginUser.password)
if(bodyLoginUser.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyLoginUser.scope)
 }
if(bodyLoginUser.client_id !== undefined && bodyLoginUser.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyLoginUser.client_id)
 }
if(bodyLoginUser.client_secret !== undefined && bodyLoginUser.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyLoginUser.client_secret)
 }

      return Fetcher<LoginUser200>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded, signal
    },
      );
    }
  


export const getLoginUserMutationOptions = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: BodyLoginUser}, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: BodyLoginUser}, TContext> => {

const mutationKey = ['loginUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginUser>>, {data: BodyLoginUser}> = (props) => {
          const {data} = props ?? {};

          return  loginUser(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginUserMutationResult = NonNullable<Awaited<ReturnType<typeof loginUser>>>
    export type LoginUserMutationBody = BodyLoginUser
    export type LoginUserMutationError = ResponseError

    /**
 * @summary Login
 */
export const createLoginUser = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof loginUser>>, TError,{data: BodyLoginUser}, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof loginUser>>,
        TError,
        {data: BodyLoginUser},
        TContext
      > => {

      const mutationOptions = getLoginUserMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * Function for refreshing token
 * @summary Refresh Token
 */
export const reauthUser = (
    reauthUserBody: ReauthUserBody,
 signal?: AbortSignal
) => {
      
      
      return Fetcher<ReauthUser200>(
      {url: `/auth/reauth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reauthUserBody, signal
    },
      );
    }
  


export const getReauthUserMutationOptions = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof reauthUser>>, TError,{data: ReauthUserBody}, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof reauthUser>>, TError,{data: ReauthUserBody}, TContext> => {

const mutationKey = ['reauthUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reauthUser>>, {data: ReauthUserBody}> = (props) => {
          const {data} = props ?? {};

          return  reauthUser(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReauthUserMutationResult = NonNullable<Awaited<ReturnType<typeof reauthUser>>>
    export type ReauthUserMutationBody = ReauthUserBody
    export type ReauthUserMutationError = ResponseError

    /**
 * @summary Refresh Token
 */
export const createReauthUser = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof reauthUser>>, TError,{data: ReauthUserBody}, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof reauthUser>>,
        TError,
        {data: ReauthUserBody},
        TContext
      > => {

      const mutationOptions = getReauthUserMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    /**
 * Function for logging out
 * @summary Logout
 */
export const logoutUser = (
    logoutUserBody: LogoutUserBody,
 signal?: AbortSignal
) => {
      
      
      return Fetcher<ResponseLogout>(
      {url: `/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: logoutUserBody, signal
    },
      );
    }
  


export const getLogoutUserMutationOptions = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,{data: LogoutUserBody}, TContext>, }
): CreateMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,{data: LogoutUserBody}, TContext> => {

const mutationKey = ['logoutUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutUser>>, {data: LogoutUserBody}> = (props) => {
          const {data} = props ?? {};

          return  logoutUser(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutUserMutationResult = NonNullable<Awaited<ReturnType<typeof logoutUser>>>
    export type LogoutUserMutationBody = LogoutUserBody
    export type LogoutUserMutationError = ResponseError

    /**
 * @summary Logout
 */
export const createLogoutUser = <TError = ResponseError,
    TContext = unknown>(options?: { mutation?:CreateMutationOptions<Awaited<ReturnType<typeof logoutUser>>, TError,{data: LogoutUserBody}, TContext>, }
 , queryClient?: QueryClient): CreateMutationResult<
        Awaited<ReturnType<typeof logoutUser>>,
        TError,
        {data: LogoutUserBody},
        TContext
      > => {

      const mutationOptions = getLogoutUserMutationOptions(options);

      return createMutation(() => ({ ...mutationOptions, queryClient }));
    }
    