/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */

/**
 * Modelo que representa un error de validación.
 */
export interface ItemError {
  /**
   * Error code identifier
   * @minLength 1
   * @maxLength 512
   */
  code: string;
  /**
   * Human-readable error message
   * @minLength 1
   * @maxLength 512
   */
  message: string;
  /**
   * Additional info about the error
   * @minLength 1
   * @maxLength 512
   */
  more_info: string;
}
