/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */

/**
 * Modelo para representar un listado de archivos de respuesta.
 */
export interface ResponseFiles {
  /** UUID del objeto */
  id: string;
  /**
   * Lista de archivos
   * @minItems 1
   * @maxItems 512
   */
  files: string[];
}
