/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response from a reauth endpoint.
 */
export interface ResponseMobile {
  /**
   * Token de refresco.
   * @minLength 36
   * @maxLength 512
   */
  refresh_token: string;
  /**
   * Tipo de token
   * @minLength 2
   * @maxLength 128
   */
  token_type?: string;
  /**
   * Token de acceso.
   * @minLength 36
   * @maxLength 512
   */
  access_token: string;
  /**
   * Indica que el reauth fue exitoso en móvil.
   * @minLength 2
   * @maxLength 256
   */
  message?: string;
}
