/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */

/**
 * Modelo para representar un mensaje de respuesta.
 */
export interface ResponseMessage {
  /**
   * Un mensaje de la api.
   * @minLength 1
   * @maxLength 256
   */
  message: string;
}
