#!/usr/bin/env bash

set -eu

MODE="${1:-}"
shift || true

if [ -f ../.env ]; then
  set -o allexport
  source ../.env
  set +o allexport
else
  echo "⚠️  Warning: .env file not found, environment variables may be missing."
fi

USER_VAR="${POSTGRES_USER:-postgres_user}"
DB_VAR="${POSTGRES_DB:-app_db}"

case "$MODE" in
  # ===========================================
  #    Populate system with default values
  # ===========================================
  --extract | -e)
    MSG="${1:-default}"
    echo "Extrae exceles de db segun modelos"
    docker compose up -d db
    echo "⏳ Waiting for database readiness (max 60s)..."
    TIMEOUT=60
    SECONDS=0
    until docker compose exec -T db pg_isready -U "$USER_VAR" -d "$DB_VAR" >/dev/null 2>&1; do
      sleep 1
      if [ $SECONDS -ge $TIMEOUT ]; then
        echo "❌ Database did not become ready after $TIMEOUT seconds."
        exit 1
      fi
      echo "   ...still waiting ($SECONDS s)"
    done
    echo "✅ Database is ready!"

    # Execute everything inside a SINGLE container lifecycle
    docker compose run --rm persister sh -c "
      echo '--- Executing extraction script ---'
      cd /api/scripts && python main.py
    "

    echo "Terminado!"
    docker compose up -d
    ;;
  # ===========================================
  #   Populate system with default values
  # ===========================================
  --setup | -s)
    MSG="${1:-default}"
    echo "🐘 Starting database container..."
    docker compose up -d db
    echo "⏳ Waiting for database readiness (max 60s)..."
    TIMEOUT=60
    SECONDS=0
    until docker compose exec -T db pg_isready -U "$USER_VAR" -d "$DB_VAR" >/dev/null 2>&1; do
      sleep 1
      if [ $SECONDS -ge $TIMEOUT ]; then
        echo "❌ Database did not become ready after $TIMEOUT seconds."
        exit 1
      fi
      echo "   ...still waiting ($SECONDS s)"
    done
    echo "✅ Database is ready!"
    echo "1️⃣  Creating schemas..."
    docker compose run --rm persister sh -c "cd /api/schemer  && python schemer.py"
    echo "2️⃣  Applying migrations (upgrade head)..."
    docker compose run --rm persister sh -c "cd /api/migrator  && alembic upgrade head"
    echo "3️⃣  Seeding tables..."
    docker compose run --rm persister sh -c "cd /api/seeder && python seeder.py"
    docker compose run --rm persister sh -c "cd /api/populator && python populator.py"
    echo "✅ Starting services..."
    docker compose up -d
    ;;
  # ===========================================
  #   Create alembic revision
  # ===========================================
  --revision | -r)
    DESC="${1:-}"
    if [ -z "$DESC" ]; then
      echo "❌ Error: Migration description required."
      echo "Usage: ./launcher.sh --revision \"add_user_bio_field\""
      exit 1
    fi

    echo "🔍 Comparing Models vs Database..."
    # We run this through the 'persister' service which has access to shared.models
    docker compose run --rm persister sh -c \
      "cd /api/migrator && alembic revision --autogenerate -m \"$DESC\""

    echo "✨ Migration script generated in Persistence/src/migrator/alembic/versions/"
    ;;

  # ===========================================
  #   Database backup and restore
  # ===========================================
  --backup | -b)
    TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
    BACKUP_DIR="./Persistence/src/backups"

    mkdir -p "$BACKUP_DIR"

    echo "Creating database backup inside $BACKUP_DIR..."

    if docker compose exec -T db sh -c "pg_dump -U \"${USER_VAR}\" -d \"${DB_VAR}\" > /backups/db_backup_$TIMESTAMP.sql"; then
      echo "✅ Backup completed successfully: $BACKUP_DIR/db_backup_$TIMESTAMP.sql"
    else
      echo "❌ Backup failed."
    fi
    ;;

  --restore | -R)
    INPUT_FILE="${1:-}"
    if [ -z "$INPUT_FILE" ]; then
      echo "Usage: ./launcher.sh --restore <backup_filename.sql or path>"
      echo "Example: ./launcher.sh --restore db_backup_20260618_232418.sql"
      exit 1
    fi

    FILE_NAME=$(basename "$INPUT_FILE")

    echo "Restoring database from $FILE_NAME..."

    # Inject PGPASSWORD so Postgres authenticates automatically without prompting
    if docker compose exec -T db sh -c "PGPASSWORD=\"\${POSTGRES_PASSWORD}\" psql -h db -U \"${USER_VAR}\" -d \"${DB_VAR}\" < /backups/$FILE_NAME"; then
      echo "✅ Restore completed successfully."
    else
      echo "❌ Restore failed. Make sure $FILE_NAME exists in your backups directory."
    fi
    ;;

  # ===========================================
  # 🆘 Help
  # ===========================================
  --help | -h | "" | *)
    cat <<EOF
Usage: $(basename "$0") [option] [args]

IIP-Visualizador Launcher — manages containers and database migrations

System & Data Operations:
    --extract,  -e             Extract Excel files from database according to models.
    --setup,    -s             Initialize database, run migrations, and seed default data.

Database Maintenance:
    --revision, -r [name]      Create an autogenerated Alembic migration revision.
    --backup,   -b             Create a timestamped SQL database backup.
    --restore,  -R [file]      Restore database from a .sql backup file.

Other Options:
    --help,     -h             Show this help message.

Examples:
    ./launcher.sh -s
    ./launcher.sh -r "add_user_table"
    ./launcher.sh -R db_backup_20260618_232418.sql
EOF
    exit 0
    ;;

esac
