/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import {
  createQuery
} from '@tanstack/svelte-query';
import type {
  CreateQueryOptions,
  CreateQueryResult,
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey
} from '@tanstack/svelte-query';

import type {
  GetAllResultsParams,
  GetOneResultsParams,
  ResponseError
} from '../../../schemas/core';

import { Fetcher } from '../../../../Fetcher';




/**
 * Obtiene una edición de índice
 * @summary Get One Form
 */
export const getOneResults = (
    params: GetOneResultsParams,
 signal?: AbortSignal
) => {
      
      
      return Fetcher<unknown>(
      {url: `/results/get/one`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetOneResultsQueryKey = (params?: GetOneResultsParams,) => {
    return [
    `/results/get/one`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetOneResultsQueryOptions = <TData = Awaited<ReturnType<typeof getOneResults>>, TError = ResponseError>(params: GetOneResultsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getOneResults>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetOneResultsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOneResults>>> = ({ signal }) => getOneResults(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getOneResults>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetOneResultsQueryResult = NonNullable<Awaited<ReturnType<typeof getOneResults>>>
export type GetOneResultsQueryError = ResponseError


/**
 * @summary Get One Form
 */

export function createGetOneResults<TData = Awaited<ReturnType<typeof getOneResults>>, TError = ResponseError>(
 params: GetOneResultsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getOneResults>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetOneResultsQueryOptions(params,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Obtiene todas las ediciones de índices
 * @summary Get All Forms
 */
export const getAllResults = (
    params?: GetAllResultsParams,
 signal?: AbortSignal
) => {
      
      
      return Fetcher<unknown>(
      {url: `/results/get/all`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetAllResultsQueryKey = (params?: GetAllResultsParams,) => {
    return [
    `/results/get/all`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetAllResultsQueryOptions = <TData = Awaited<ReturnType<typeof getAllResults>>, TError = ResponseError>(params?: GetAllResultsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllResults>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllResultsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllResults>>> = ({ signal }) => getAllResults(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as CreateQueryOptions<Awaited<ReturnType<typeof getAllResults>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAllResultsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllResults>>>
export type GetAllResultsQueryError = ResponseError


/**
 * @summary Get All Forms
 */

export function createGetAllResults<TData = Awaited<ReturnType<typeof getAllResults>>, TError = ResponseError>(
 params?: GetAllResultsParams, options?: { query?:Partial<CreateQueryOptions<Awaited<ReturnType<typeof getAllResults>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ): CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAllResultsQueryOptions(params,options)

  const query = createQuery(() => ({ ...queryOptions, queryClient })) as CreateQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




