services:
  api_ia_agent:
    image: labcapital/apps:IIP-IA-Agent
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - github_token_commons
        - github_token_iip

secrets:
  github_token_commons:
    environment: GITHUB_TOKEN_COMMONS
  github_token_iip:
    environment: GITHUB_TOKEN_IIP



