/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetAllFormsParams,
  GetOneFormParams,
  ResponseForm,
  ResponseForms
} from '../../../schemas/core';

import { Fetcher } from '../../../../Fetcher';



  export const getFormularios = () => {
/**
 * Obtiene una edición de índice
 * @summary Get One Form
 */
const getOneForm = (
    params: GetOneFormParams,
 ) => {
      return Fetcher<ResponseForm>(
      {url: `/forms/get/one`, method: 'GET',
        params
    },
      );
    }
  /**
 * Obtiene todas las ediciones de índices
 * @summary Get All Forms
 */
const getAllForms = (
    params?: GetAllFormsParams,
 ) => {
      return Fetcher<ResponseForms>(
      {url: `/forms/get/all`, method: 'GET',
        params
    },
      );
    }
  return {getOneForm,getAllForms}};
export type GetOneFormResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFormularios>['getOneForm']>>>
export type GetAllFormsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFormularios>['getAllForms']>>>
