/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type {
  BodyLoginUser,
  LoginUser200,
  LogoutUserBody,
  ReauthUser200,
  ReauthUserBody,
  RequestRegister,
  ResponseLogout,
  ResponseRegister
} from '../../../schemas/auth';

import { Fetcher } from '../../../../Fetcher';



  export const getAutenticación = () => {
/**
 * Function for registering
 * @summary Register
 */
const registerUser = (
    requestRegister: RequestRegister,
 ) => {const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`password`, requestRegister.password)
formUrlEncoded.append(`email`, requestRegister.email)
formUrlEncoded.append(`username`, requestRegister.username)

      return Fetcher<ResponseRegister>(
      {url: `/auth/register`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded
    },
      );
    }
  /**
 * Function for logging in
 * @summary Login
 */
const loginUser = (
    bodyLoginUser: BodyLoginUser,
 ) => {const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`grant_type`, bodyLoginUser.grant_type)
formUrlEncoded.append(`username`, bodyLoginUser.username)
formUrlEncoded.append(`password`, bodyLoginUser.password)
if(bodyLoginUser.scope !== undefined) {
 formUrlEncoded.append(`scope`, bodyLoginUser.scope)
 }
if(bodyLoginUser.client_id !== undefined && bodyLoginUser.client_id !== null) {
 formUrlEncoded.append(`client_id`, bodyLoginUser.client_id)
 }
if(bodyLoginUser.client_secret !== undefined && bodyLoginUser.client_secret !== null) {
 formUrlEncoded.append(`client_secret`, bodyLoginUser.client_secret)
 }

      return Fetcher<LoginUser200>(
      {url: `/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/x-www-form-urlencoded', },
       data: formUrlEncoded
    },
      );
    }
  /**
 * Function for refreshing token
 * @summary Refresh Token
 */
const reauthUser = (
    reauthUserBody: ReauthUserBody,
 ) => {
      return Fetcher<ReauthUser200>(
      {url: `/auth/reauth`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: reauthUserBody
    },
      );
    }
  /**
 * Function for logging out
 * @summary Logout
 */
const logoutUser = (
    logoutUserBody: LogoutUserBody,
 ) => {
      return Fetcher<ResponseLogout>(
      {url: `/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: logoutUserBody
    },
      );
    }
  return {registerUser,loginUser,reauthUser,logoutUser}};
export type RegisterUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutenticación>['registerUser']>>>
export type LoginUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutenticación>['loginUser']>>>
export type ReauthUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutenticación>['reauthUser']>>>
export type LogoutUserResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAutenticación>['logoutUser']>>>
