services:
  front_stats_dev:
    container_name: iip_stats_dev
    env_file: ./.env
    build:
      context: .
      dockerfile: Dockerfile.dev
    networks:
      - iip_nginx
    ports:
      - "5173:5173"
    profiles:
      - dev
    volumes:
      - ./stats/src:/usr/src/app/src
      - ./stats/static:/usr/src/app/static

  front_stats:
    image: labcapital/apps:IIP-Stats
    build:
      context: .
      dockerfile: Dockerfile
    profiles:
      - prod

networks:
  iip_nginx:
    external: true
    name: iip_nginx_network
