"""'interactions'

Revision ID: 539143a3033a
Revises: 
Create Date: 2025-11-14 16:43:22.794616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '539143a3033a'
down_revision: str = '539143a3032e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('notification_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('comments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('comment_type_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.Enum('ACTOR_SEGMENTS', 'ACTORS', 'LOGS', 'USERS', 'REFRESH_SESSIONS', 'USER_DETAILS', 'USER_PROFILES', 'FILES', 'CARD_TEMPLATES', 'FIELD_CHOICES', 'FIELD_GROUPS', 'FIELDS', 'FORMS', 'INFORMATIONS', 'QUESTIONS', 'SECTIONS', 'SECTION_TYPES', 'ASSIGNMENTS', 'CRITERIA', 'GRADES', 'RESULTS', 'COMMENTS', 'NOTIFICATIONS', 'LINK_CHOICE_MULTICHOICE', 'LINK_USER_ACTOR', 'LINK_USER_SUBMISSION', 'LINK_USER_FILE', 'FIELD_DEPENDENCIES', 'SECTION_DEPENDENCIES', 'FIELD_RULES', 'COMMENT_TYPES', 'FIELD_TYPES', 'FILE_TYPES', 'LOG_ACTION_TYPES', 'NOTIFICATION_TYPES', 'RELATIONAL_OPERATORS', 'ROLES', 'SUBMISSION_STATUS_TYPES', 'USER_TIERS', 'VALIDATION_TYPES', 'ANSWERS', 'ANSWERS_BOOLEAN', 'ANSWERS_CARD_ENTRY', 'ANSWERS_DATE', 'ANSWERS_FILE', 'ANSWERS_MULTI_CHOICE', 'ANSWERS_NUMERIC', 'ANSWERS_SINGLE_CHOICE', 'ANSWERS_TEXT', 'SUBMISSIONS', name='targettable'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['comment_type_id'], ['reference.comment_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='interactions'
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['notification_type_id'], ['reference.notification_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='interactions'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications', schema='interactions')
    op.drop_table('comments', schema='interactions')
    op.drop_table('notification_types', schema='reference')
    op.drop_table('comment_types', schema='reference')
    # ### end Alembic commands ###
