"""'grading'

Revision ID: 539143a3032d
Revises: 
Create Date: 2025-11-14 16:43:22.794616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '539143a3032d'
down_revision: str = '539143a3032c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submission_status_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('submissions',
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.forms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['status_id'], ['reference.submission_status_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('criteria',
    sa.Column('target', sa.Enum('ACTOR_SEGMENTS', 'ACTORS', 'LOGS', 'USERS', 'REFRESH_SESSIONS', 'USER_DETAILS', 'USER_PROFILES', 'FILES', 'CARD_TEMPLATES', 'FIELD_CHOICES', 'FIELD_GROUPS', 'FIELDS', 'FORMS', 'INFORMATIONS', 'QUESTIONS', 'SECTIONS', 'SECTION_TYPES', 'ASSIGNMENTS', 'CRITERIA', 'GRADES', 'RESULTS', 'COMMENTS', 'NOTIFICATIONS', 'LINK_CHOICE_MULTICHOICE', 'LINK_USER_ACTOR', 'LINK_USER_SUBMISSION', 'LINK_USER_FILE', 'FIELD_DEPENDENCIES', 'SECTION_DEPENDENCIES', 'FIELD_RULES', 'COMMENT_TYPES', 'FIELD_TYPES', 'FILE_TYPES', 'LOG_ACTION_TYPES', 'NOTIFICATION_TYPES', 'RELATIONAL_OPERATORS', 'ROLES', 'SUBMISSION_STATUS_TYPES', 'USER_TIERS', 'VALIDATION_TYPES', 'ANSWERS', 'ANSWERS_BOOLEAN', 'ANSWERS_CARD_ENTRY', 'ANSWERS_DATE', 'ANSWERS_FILE', 'ANSWERS_MULTI_CHOICE', 'ANSWERS_NUMERIC', 'ANSWERS_SINGLE_CHOICE', 'ANSWERS_TEXT', 'SUBMISSIONS', name='targettable'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('weight', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='grading'
    )
    op.create_table('grades',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('criteria_id', sa.UUID(), nullable=False),
    sa.Column('grade', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['criteria_id'], ['grading.criteria.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submissions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='grading'
    )
    op.create_table('results',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('final_score', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='grading'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results', schema='grading')
    op.drop_table('grades', schema='grading')
    op.drop_table('criteria', schema='grading')
    op.drop_table('submissions', schema='submissions')
    op.drop_table('submission_status_types', schema='reference')
    # ### end Alembic commands ###
