"""'auth'

Revision ID: 539143a3031a
Revises: 
Create Date: 2025-11-14 16:43:22.794616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '539143a3031a'
down_revision: str = '539143a3030a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('tier_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('media_usage', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tier_id'], ['reference.user_tiers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    schema='auth'
    )
    op.create_table('logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('log_action_type_id', sa.UUID(), nullable=False),
    sa.Column('target', sa.Enum('ACTOR_SEGMENTS', 'ACTORS', 'LOGS', 'USERS', 'REFRESH_SESSIONS', 'USER_DETAILS', 'USER_PROFILES', 'FILES', 'CARD_TEMPLATES', 'FIELD_CHOICES', 'FIELD_GROUPS', 'FIELDS', 'FORMS', 'INFORMATIONS', 'QUESTIONS', 'SECTIONS', 'SECTION_TYPES', 'ASSIGNMENTS', 'CRITERIA', 'GRADES', 'RESULTS', 'COMMENTS', 'NOTIFICATIONS', 'LINK_CHOICE_MULTICHOICE', 'LINK_USER_ACTOR', 'LINK_USER_SUBMISSION', 'LINK_USER_FILE', 'FIELD_DEPENDENCIES', 'SECTION_DEPENDENCIES', 'FIELD_RULES', 'COMMENT_TYPES', 'FIELD_TYPES', 'FILE_TYPES', 'LOG_ACTION_TYPES', 'NOTIFICATION_TYPES', 'RELATIONAL_OPERATORS', 'ROLES', 'SUBMISSION_STATUS_TYPES', 'USER_TIERS', 'VALIDATION_TYPES', 'ANSWERS', 'ANSWERS_BOOLEAN', 'ANSWERS_CARD_ENTRY', 'ANSWERS_DATE', 'ANSWERS_FILE', 'ANSWERS_MULTI_CHOICE', 'ANSWERS_NUMERIC', 'ANSWERS_SINGLE_CHOICE', 'ANSWERS_TEXT', 'SUBMISSIONS', name='targettable'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['log_action_type_id'], ['reference.log_action_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='audit'
    )
    op.create_table('refresh_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('jti', sa.UUID(), nullable=False),
    sa.Column('refresh_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('user_details',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email_pro', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('area', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_pro'),
    sa.UniqueConstraint('user_id'),
    schema='auth'
    )
    op.create_table('files',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_type_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=64), nullable=False),
    sa.Column('filepath', sa.String(length=255), nullable=False),
    sa.Column('filehash', sa.String(length=64), nullable=False),
    sa.Column('filesize', sa.Numeric(precision=15, scale=0), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_type_id'], ['reference.file_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='files'
    )
    op.create_index(op.f('ix_files_files_filehash'), 'files', ['filehash'], unique=True, schema='files')
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id'),
    sa.UniqueConstraint('user_id'),
    schema='auth'
    )
    op.create_table('user_file_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['reference.roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'file_id', 'role_id', 'id'),
    schema='links'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_file_links', schema='links')
    op.drop_table('user_profiles', schema='auth')
    op.drop_index(op.f('ix_files_files_filehash'), table_name='files', schema='files')
    op.drop_table('files', schema='files')
    op.drop_table('user_details', schema='auth')
    op.drop_table('refresh_sessions', schema='auth')
    op.drop_table('logs', schema='audit')
    op.drop_table('users', schema='auth')
    # ### end Alembic commands ###
