"""'submissions'

Revision ID: 539143a3032e
Revises: 
Create Date: 2025-11-14 16:43:22.794616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '539143a3032e'
down_revision: str = '539143a3032d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answers_card_entry',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('card_template_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('card_index', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_template_id'], ['forms.card_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['forms.questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('answers',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('card_entry_id', sa.UUID(), nullable=True),
    sa.Column('value_table', sa.Enum('ACTOR_SEGMENTS', 'ACTORS', 'LOGS', 'USERS', 'REFRESH_SESSIONS', 'USER_DETAILS', 'USER_PROFILES', 'FILES', 'CARD_TEMPLATES', 'FIELD_CHOICES', 'FIELD_GROUPS', 'FIELDS', 'FORMS', 'INFORMATIONS', 'QUESTIONS', 'SECTIONS', 'SECTION_TYPES', 'ASSIGNMENTS', 'CRITERIA', 'GRADES', 'RESULTS', 'COMMENTS', 'NOTIFICATIONS', 'LINK_CHOICE_MULTICHOICE', 'LINK_USER_ACTOR', 'LINK_USER_SUBMISSION', 'LINK_USER_FILE', 'FIELD_DEPENDENCIES', 'SECTION_DEPENDENCIES', 'FIELD_RULES', 'COMMENT_TYPES', 'FIELD_TYPES', 'FILE_TYPES', 'LOG_ACTION_TYPES', 'NOTIFICATION_TYPES', 'RELATIONAL_OPERATORS', 'ROLES', 'SUBMISSION_STATUS_TYPES', 'USER_TIERS', 'VALIDATION_TYPES', 'ANSWERS', 'ANSWERS_BOOLEAN', 'ANSWERS_CARD_ENTRY', 'ANSWERS_DATE', 'ANSWERS_FILE', 'ANSWERS_MULTI_CHOICE', 'ANSWERS_NUMERIC', 'ANSWERS_SINGLE_CHOICE', 'ANSWERS_TEXT', 'SUBMISSIONS', name='targettable'), nullable=False),
    sa.Column('value_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_entry_id'], ['submissions.answers_card_entry.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['forms.fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('answers_boolean',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['submissions.answers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('answers_date',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['submissions.answers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('answers_file',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('value_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['submissions.answers.id'], ),
    sa.ForeignKeyConstraint(['value_id'], ['files.files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('answers_multi_choice',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['submissions.answers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('answers_numeric',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['submissions.answers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('answers_single_choice',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('value_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['submissions.answers.id'], ),
    sa.ForeignKeyConstraint(['value_id'], ['forms.field_choices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('answers_texts',
    sa.Column('answer_id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['submissions.answers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='submissions'
    )
    op.create_table('choice_multichoice_links',
    sa.Column('choice_id', sa.UUID(), nullable=False),
    sa.Column('multi_choice_answer_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['choice_id'], ['forms.field_choices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['multi_choice_answer_id'], ['submissions.answers_multi_choice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('choice_id', 'multi_choice_answer_id', 'id'),
    schema='links'
    )
    op.create_table('user_actor_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['reference.roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'actor_id', 'role_id', 'id'),
    schema='links'
    )
    op.create_table('user_submission_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['reference.roles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'submission_id', 'role_id', 'id'),
    schema='links'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_submission_links', schema='links')
    op.drop_table('user_actor_links', schema='links')
    op.drop_table('choice_multichoice_links', schema='links')
    op.drop_table('answers_texts', schema='submissions')
    op.drop_table('answers_single_choice', schema='submissions')
    op.drop_table('answers_numeric', schema='submissions')
    op.drop_table('answers_multi_choice', schema='submissions')
    op.drop_table('answers_file', schema='submissions')
    op.drop_table('answers_date', schema='submissions')
    op.drop_table('answers_boolean', schema='submissions')
    op.drop_table('answers', schema='submissions')
    op.drop_table('answers_card_entry', schema='submissions')
    # ### end Alembic commands ###
