"""'rules'

Revision ID: 539143a3032c
Revises: 
Create Date: 2025-11-14 16:43:22.794616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '539143a3032c'
down_revision: str = '539143a3032b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relational_operators',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('rule_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('section_dependencies',
    sa.Column('target_section_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_section_id', sa.UUID(), nullable=False),
    sa.Column('relational_operator_id', sa.UUID(), nullable=False),
    sa.Column('expected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_section_id'], ['forms.sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relational_operator_id'], ['reference.relational_operators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_section_id'], ['forms.sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rules'
    )
    op.create_table('field_dependencies',
    sa.Column('target_field_id', sa.UUID(), nullable=False),
    sa.Column('depends_on_field_id', sa.UUID(), nullable=False),
    sa.Column('relational_operator_id', sa.UUID(), nullable=False),
    sa.Column('expected_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_field_id'], ['forms.fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relational_operator_id'], ['reference.relational_operators.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['target_field_id'], ['forms.fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rules'
    )
    op.create_table('field_rules',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('rule_type_id', sa.UUID(), nullable=False),
    sa.Column('rule_value', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['forms.fields.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_type_id'], ['reference.rule_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='rules'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_rules', schema='rules')
    op.drop_table('field_dependencies', schema='rules')
    op.drop_table('section_dependencies', schema='rules')
    op.drop_table('validation_types', schema='reference')
    op.drop_table('relational_operators', schema='reference')
    # ### end Alembic commands ###
