"""'forms'

Revision ID: 539143a3032b
Revises: 
Create Date: 2025-11-14 16:43:22.794616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '539143a3032b'
down_revision: str = '539143a3032a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('forms',
    sa.Column('anno', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anno'),
    schema='forms'
    )
    op.create_table('section_types',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_table('sections',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('section_type_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('helper', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.forms.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['forms.sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_type_id'], ['forms.section_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_index('idx_sections_form_id', 'sections', ['form_id'], unique=False, schema='forms')
    op.create_index('idx_sections_parent_display_order', 'sections', ['parent_id', 'display_order'], unique=False, schema='forms')
    op.create_index('idx_sections_parent_id', 'sections', ['parent_id'], unique=False, schema='forms')
    op.create_index('idx_sections_section_type_id', 'sections', ['section_type_id'], unique=False, schema='forms')
    op.create_table('information',
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['forms.sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_table('questions',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('section_id', sa.UUID(), nullable=False),
    sa.Column('is_loop', sa.Boolean(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('helper', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.forms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['forms.sections.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_table('card_templates',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('helper', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['forms.questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_table('field_groups',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('card_template_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['card_template_id'], ['forms.card_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.forms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['forms.questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_table('fields',
    sa.Column('form_id', sa.UUID(), nullable=False),
    sa.Column('field_group_id', sa.UUID(), nullable=False),
    sa.Column('field_type_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['field_group_id'], ['forms.field_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_type_id'], ['reference.field_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['form_id'], ['forms.forms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    op.create_table('field_choices',
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['forms.fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='forms'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_choices', schema='forms')
    op.drop_table('fields', schema='forms')
    op.drop_table('field_groups', schema='forms')
    op.drop_table('card_templates', schema='forms')
    op.drop_table('questions', schema='forms')
    op.drop_table('information', schema='forms')
    op.drop_index('idx_sections_section_type_id', table_name='sections', schema='forms')
    op.drop_index('idx_sections_parent_id', table_name='sections', schema='forms')
    op.drop_index('idx_sections_parent_display_order', table_name='sections', schema='forms')
    op.drop_index('idx_sections_form_id', table_name='sections', schema='forms')
    op.drop_table('sections', schema='forms')
    op.drop_table('section_types', schema='forms')
    op.drop_table('forms', schema='forms')
    op.drop_table('field_types', schema='reference')
    # ### end Alembic commands ###
