/**
 * Generated by orval v7.16.1 🍺
 * Do not edit manually.
 * Servicios privados para stats
 * API para stats
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetAllActorsParams,
  GetOneActorParams,
  ResponseActor,
  ResponseActors
} from '../../../schemas/core';

import { Fetcher } from '../../../../Fetcher';



  export const getActores = () => {
/**
 * Obtiene una entidad por su ID
 * @summary Get One Actor
 */
const getOneActor = (
    params: GetOneActorParams,
 ) => {
      return Fetcher<ResponseActor>(
      {url: `/actors/get/one`, method: 'GET',
        params
    },
      );
    }
  /**
 * Obtiene todas las entidades
 * @summary Get All Actors
 */
const getAllActors = (
    params?: GetAllActorsParams,
 ) => {
      return Fetcher<ResponseActors>(
      {url: `/actors/get/all`, method: 'GET',
        params
    },
      );
    }
  return {getOneActor,getAllActors}};
export type GetOneActorResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getActores>['getOneActor']>>>
export type GetAllActorsResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getActores>['getAllActors']>>>
